### PR TITLE
Removed package-lock.json and standardize to Yarn. Fixes #29

### LINKED ISSUE #29: Remove duplicate lockfile
There's both NPM lockfile (`package-lock.json`) and Yarn lockfile (`yarn.lock`) – can we remove the former and standardize to Yarn?

### PR DESCRIPTION
**Pull request by wdym69**
Removed package-lock.json and added it to .gitignore.

### CODE REVIEW

**Comment by martin-henz** [comment]
The package-lock.json file should be committed to ensure consistent installs across all environments. This file locks dependency versions, improving reproducibility and build stability for Source Academy.

**Comment by wdym69** [comment]
Thankyou for the comment @martin-henz . 
The issue #29 suggests to remove the NPM lockfile (`package-lock.json`) and standardize to Yarn, hence i did that.
If that seems incorrect, what could be the solution to this issue?

**Comment by martin-henz** [comment]
Oh, yes. This is good. Sorry for misunderstanding.

**Comment by martin-henz** [comment]
Oh, yes. This is good. Sorry for misunderstanding.

**Pull request merged**
